import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut,updatePassword} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,collection,doc,getDoc,getDocs,query,where,orderBy,setDoc,updateDoc,deleteDoc,onSnapshot,enableIndexedDbPersistence,serverTimestamp,writeBatch} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
const cfg=window.FAMILY_APP_CONFIG, $=s=>document.querySelector(s), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), day=()=>new Date().toLocaleDateString('sv-SE'),id=()=>crypto.randomUUID(),money=n=>n===''||n==null?'待填金額':'NT$ '+Number(n).toLocaleString('zh-TW');
const S={tab:'home',scope:'shared',date:day().slice(0,7),selected:day(),year:new Date().getFullYear(),yearMode:'grid',user:null,role:'member',member:null,data:{bills:[],events:[],templates:[],members:[]},unsubs:[],edit:null,editType:null,notice:''};
const configured=cfg&&cfg.apiKey&&cfg.apiKey!=='REPLACE_ME'&&cfg.projectId!=='REPLACE_ME';let auth,db;
const familyPath=()=>`families/${cfg.familyId}`, itemsPath=(kind,scope=S.scope)=>scope==='shared'?`${familyPath()}/${kind}`:`users/${S.user.uid}/${kind}`;
function err(e){console.error(e);S.notice=e?.message||String(e);render()}
function addMonths(src,n){const [y,m,d]=src.split('-').map(Number);const t=new Date(y,m-1+n,1),max=new Date(t.getFullYear(),t.getMonth()+1,0).getDate();t.setDate(Math.min(d,max));return t.toLocaleDateString('sv-SE')}
function currentMonthBills(){return S.data.bills.filter(x=>x.dueDate?.slice(0,7)===S.date).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))}
function currentMonthEvents(){return S.data.events.filter(x=>x.date?.slice(0,7)===S.date).sort((a,b)=>a.date.localeCompare(b.date))}
function totals(items){return {due:items.reduce((n,x)=>n+(Number(x.amount)||0),0),paid:items.filter(x=>x.paid).reduce((n,x)=>n+(Number(x.amount)||0),0),open:items.filter(x=>!x.paid).length,blank:items.filter(x=>x.amount==null||x.amount==='').length}}
function statBox(k,v){return `<div class="card stat"><small>${k}</small><strong>${v}</strong></div>`}
function statView(list){const a=totals(list);return `<div class="stats">${statBox('應繳金額',money(a.due))}${statBox('已繳金額',money(a.paid))}${statBox('待繳筆數',a.open+' 筆')}${statBox('待填金額',a.blank+' 筆')}</div>`}
function billRow(x){const status=x.deleted?'回收區':x.paid?'已繳':x.dueDate<day()?'逾期':x.amount==null?'待填金額':'待繳';return `<div class="listitem"><div><strong>${E(x.name)} <span class="pill ${x.deleted?'red':x.paid?'green':'warn'}">${status}</span></strong><small>${E(x.dueDate)} · ${E(x.category||'生活')}${x.paidDate?' · 實際繳費 '+E(x.paidDate):''}</small></div><div class="right"><strong>${money(x.amount)}</strong><button data-edit="bills" data-id="${E(x.id)}">編輯</button></div></div>`}
function eventRow(x){return `<div class="listitem"><div><strong>${E(x.title)}</strong><small>${E(x.date)} ${E(x.time||'')} · ${E(x.category||'生活')}${x.note?' · '+E(x.note):''}</small></div><button data-edit="events" data-id="${E(x.id)}">編輯</button></div>`}
function records(list,fn,empty='暫無資料'){return list.length?list.map(fn).join(''):`<div class="muted">${empty}</div>`}
function tabs(){return `<div class="toolbar"><div><button data-scope="shared" class="${S.scope==='shared'?'primary':''}">家庭共用</button> <button data-scope="private" class="${S.scope==='private'?'primary':''}">我的私人</button></div><span class="pill">${S.scope==='shared'?'全家可新增修改刪除':'僅本人可存取'}</span></div>`}
function home(){const b=currentMonthBills(),ev=currentMonthEvents();const reminder=b.filter(x=>!x.paid&&x.dueDate<=addDays(day(),7)).slice(0,6);return `${tabs()}<h2>${S.date.replace('-',' 年 ')} 月總覽</h2>${statView(b)}<div class="grid"><section class="card"><h3>近期待繳</h3>${records(reminder,billRow,'沒有近期待繳項目')}</section><section class="card"><h3>本月記事</h3>${records(ev.slice(0,8),eventRow,'沒有記事')}</section></div>`}
function addDays(d,n){const dt=new Date(d+'T12:00:00');dt.setDate(dt.getDate()+n);return dt.toLocaleDateString('sv-SE')}
function monthNav(){return `<div class="toolbar"><button data-month="-1">‹ 上個月</button><strong>${S.date.replace('-',' 年 ')} 月</strong><button data-month="1">下個月 ›</button></div>`}
function bills(){return `${tabs()}${monthNav()}${statView(currentMonthBills())}<div class="row"><h2>繳費紀錄</h2><button class="primary" data-add="bills">＋ 新增繳費</button></div><div class="card">${records(currentMonthBills(),billRow)}</div><div class="row"><h2>固定繳費設定</h2><button data-add="templates">＋ 新增固定項目</button></div><div class="card">${records(S.data.templates,x=>`<div class="listitem"><div><strong>${E(x.name)}</strong><small>${E(x.startDate)} 起 · 每 ${x.cycle} 個月 · ${x.active===false?'已停用':'啟用'}</small></div><button data-edit="templates" data-id="${E(x.id)}">編輯</button></div>`)}</div>`}
function calendar(){const [y,m]=S.date.split('-').map(Number),offset=new Date(y,m-1,1).getDay(),count=new Date(y,m,0).getDate();let html=['日','一','二','三','四','五','六'].map(d=>`<div class="weekday">${d}</div>`).join('');html+='<div></div>'.repeat(offset);for(let i=1;i<=count;i++){const d=`${S.date}-${String(i).padStart(2,'0')}`,b=S.data.bills.filter(x=>x.dueDate===d).length,e=S.data.events.filter(x=>x.date===d).length;html+=`<button class="day ${S.selected===d?'current':''}" data-date="${d}">${i}<div class="daynote">${b?'繳'+b+' ':''}${e?'事'+e:''}</div></button>`}const bs=S.data.bills.filter(x=>x.dueDate===S.selected),es=S.data.events.filter(x=>x.date===S.selected);return `${tabs()}${monthNav()}<div class="card"><div class="calendar">${html}</div></div><div class="row"><h2>${S.selected} 明細</h2><button data-add="events">＋ 新增記事</button></div><div class="card"><h3>重要記事</h3>${records(es,eventRow)}</div><div class="card"><h3>當日繳費</h3>${records(bs,billRow)}</div>`}
function year(){const months=Array.from({length:12},(_,i)=>`${S.year}-${String(i+1).padStart(2,'0')}`),content=months.map((m,i)=>{const b=S.data.bills.filter(x=>x.dueDate?.startsWith(m)),e=S.data.events.filter(x=>x.date?.startsWith(m));return `<button class="month ${S.date===m?'current':''}" data-gomonth="${m}"><strong>${i+1} 月</strong><small>${money(totals(b).due)}</small><small>${e.length} 項記事 · ${totals(b).open} 筆未繳</small></button>`}).join('');const yearBills=S.data.bills.filter(x=>x.dueDate?.startsWith(S.year+'-'));return `${tabs()}<div class="toolbar"><button data-year="-1">‹</button><h2>${S.year} 年度總覽</h2><button data-year="1">›</button></div>${statView(yearBills)}<div class="toolbar"><button data-yearmode="grid" class="${S.yearMode==='grid'?'primary':''}">方格</button><button data-yearmode="list" class="${S.yearMode==='list'?'primary':''}">清單</button></div><div class="${S.yearMode==='grid'?'months':'stack'}">${content}</div><section class="card spaced"><h3>${S.date.replace('-',' 年 ')} 月繳費與記事</h3><h3>繳費</h3>${records(currentMonthBills(),billRow)}<h3>記事</h3>${records(currentMonthEvents(),eventRow)}</section>`}
function settings(){return `${tabs()}<section class="card"><h2>備份與匯出</h2><p class="muted">JSON 備份僅包含目前選取的「${S.scope==='shared'?'家庭共用':'我的私人'}」資料。匯入預設採相同範圍，請勿將私人備份匯入共用區。</p><button data-action="export">匯出 JSON</button> <button data-action="import">匯入 JSON</button> <button data-action="csv">匯出繳費 CSV</button><input id="importFile" type="file" accept="application/json,.json" hidden></section><section class="card"><h2>資料設定</h2><p>目前使用者：${E(S.user?.email)}</p><p>角色：${S.role==='admin'?'管理者':'家庭成員'}</p><button data-action="password">修改我的登入密碼</button></section>`}
function admin(){if(S.role!=='admin')return '<div class="card">沒有管理者權限</div>';return `<section class="card"><h2>家庭成員管理（Spark 免費版）</h2><p>帳號須由管理者在 Firebase 控制台 → Authentication → 使用者 → 新增使用者建立；再在 Firestore 建立對應的家庭成員文件。</p><p class="muted">成員文件路徑：families/home/members/{使用者UID}，欄位 uid（字串）、name（字串）、role（member）、active（布林值 true）、email（字串）。停用時請先在 Firestore 將 active 改為 false，再於 Authentication 停用帳號；此頁僅顯示狀態。</p></section><section class="card"><h2>家庭成員</h2>${records(S.data.members,x=>`<div class="listitem"><div><strong>${E(x.name||x.email||x.uid)}</strong><small>${E(x.email||x.uid)} · ${x.role==='admin'?'管理者':'一般成員'} · ${x.active===false?'停用':'啟用'}</small></div></div>`)}</section><section class="card"><h2>共同資料維護</h2><p class="muted">成員刪除共同資料會移至回收區，管理者可在此還原。</p><button data-action="trash">查看回收區</button><div id="trashOutput"></div></section>`}
function render(){if(!S.user)return;$('#profile').innerHTML=`<div class="right"><small>${E(S.user.email)}</small><div><button data-action="signout">登出</button></div></div>`;$('#message').innerHTML=S.notice?`<div class="notice">${E(S.notice)} <button data-action="dismiss">關閉</button></div>`:'';const routes={home,bills,calendar,year,settings,admin};$('#app').innerHTML=(routes[S.tab]||home)();$('#nav').hidden=false;$('#nav').innerHTML=[['home','首頁'],['bills','繳費'],['calendar','月曆'],['year','年度'],['settings','設定'],...(S.role==='admin'?[['admin','管理']]:[])].map(([k,v])=>`<button data-tab="${k}" class="${S.tab===k?'active':''}">${v}</button>`).join('')}
function loginScreen(){ $('#profile').innerHTML='';$('#nav').hidden=true;$('#app').innerHTML=`<section class="card signin"><h2>家庭成員登入</h2><form id="loginForm"><label>Email</label><input name="email" type="email" autocomplete="username" required><label>密碼</label><input name="password" type="password" autocomplete="current-password" required><button type="submit" class="primary spaced">登入</button></form><p class="muted">帳號由家庭管理者建立，無公開註冊功能。</p></section>`}
function inputs(type,obj={}){const f=(name,label,type='text',value='',attrs='')=>`<label>${label}</label><input name="${name}" type="${type}" value="${E(value)}" ${attrs}>`,sel=(name,label,options,value)=>`<label>${label}</label><select name="${name}">${options.map(([a,b])=>`<option value="${E(a)}" ${String(a)===String(value)?'selected':''}>${E(b)}</option>`).join('')}</select>`;if(type==='bills')return f('name','繳費名稱','text',obj.name,'required maxlength="80"')+f('category','分類','text',obj.category||'生活')+f('dueDate','繳費期限','date',obj.dueDate||S.selected,'required')+f('amount','本期金額（可留空）','number',obj.amount??'','min="0" step="1"')+sel('paid','繳費狀態',[['false','未繳'],['true','已繳']],String(!!obj.paid))+f('paidDate','實際繳費日期','date',obj.paidDate||'');if(type==='templates')return f('name','固定項目名稱','text',obj.name,'required maxlength="80"')+f('category','分類','text',obj.category||'生活')+f('startDate','首次繳費期限','date',obj.startDate||day(),'required')+sel('cycle','週期（月）',[[1,'每月'],[2,'每 2 個月'],[3,'每季'],[6,'每半年'],[12,'每年']],obj.cycle||1)+sel('active','是否啟用',[['true','啟用'],['false','停用']],String(obj.active!==false));return f('title','記事標題','text',obj.title,'required maxlength="100"')+f('date','日期','date',obj.date||S.selected,'required')+f('time','時間','time',obj.time||'')+f('category','分類','text',obj.category||'生活')+sel('remindDays','APP 內提醒',[['','不提醒'],[0,'當天'],[1,'提前 1 天'],[3,'提前 3 天'],[7,'提前 7 天']],obj.remindDays??1)+`<label>備註</label><textarea name="note" maxlength="2000">${E(obj.note||'')}</textarea>`}
function edit(type,itemId){S.editType=type;S.edit=itemId?S.data[type].find(x=>x.id===itemId):null;$('#editorTitle').textContent=(S.edit?'編輯':'新增')+({bills:'繳費',events:'記事',templates:'固定項目'}[type]);$('#entryFields').innerHTML=inputs(type,S.edit||{});$('#deleteEntry').hidden=!S.edit;$('#editor').showModal()}
async function save(e){e.preventDefault();const form=new FormData(e.target),obj={...(S.edit||{}),id:S.edit?.id||id(),scope:S.scope,updatedAt:new Date().toISOString()};for(const [k,v]of form)obj[k]=typeof v==='string'?v.trim():v;if(S.editType==='bills'){obj.paid=obj.paid==='true';obj.amount=obj.amount===''?null:Number(obj.amount);if(obj.paid&&!obj.paidDate)obj.paidDate=day();if(!obj.paid)obj.paidDate=''}if(S.editType==='templates'){obj.cycle=Number(obj.cycle);obj.active=obj.active==='true'}if(S.editType==='events')obj.remindDays=obj.remindDays===''?'':Number(obj.remindDays);if(!obj.createdAt)obj.createdAt=obj.updatedAt;await setDoc(doc(db,itemsPath(S.editType),obj.id),obj);$('#editor').close();if(S.editType==='templates')await generate();}
async function del(){if(!S.edit||!confirm('確定刪除這筆資料？'))return;const ref=doc(db,itemsPath(S.editType),S.edit.id);if(S.scope==='shared')await updateDoc(ref,{deleted:true,deletedAt:new Date().toISOString()});else await deleteDoc(ref);$('#editor').close()}
function listen(){S.unsubs.forEach(f=>f());S.unsubs=[];for(const kind of ['bills','events','templates']){S.unsubs.push(onSnapshot(collection(db,itemsPath(kind)),snap=>{S.data[kind]=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>!x.deleted);render();if(kind==='templates')generate().catch(console.error)},err))}if(S.role==='admin'){S.unsubs.push(onSnapshot(collection(db,`${familyPath()}/members`),snap=>{S.data.members=snap.docs.map(d=>({uid:d.id,...d.data()}));render()},err))}}
let generating=false;
async function generate(){
  if(generating||!S.user||!S.data.templates.length)return;
  generating=true;
  const scope=S.scope;
  try{
    const first=day().slice(0,7)+'-01',until=addMonths(first,12);
    for(const t of S.data.templates){
      if(t.active===false||!t.startDate||![1,2,3,6,12].includes(Number(t.cycle)))continue;
      const cycle=Number(t.cycle);
      for(let n=0;n<240;n++){
        const due=addMonths(t.startDate,n*cycle);
        if(due>until)break;
        if(due<first)continue;
        const entryId=`rec_${t.id}_${due}`,ref=doc(db,itemsPath('bills',scope),entryId);
        if((await getDoc(ref)).exists())continue;
        // deterministic ID, only write when missing; concurrent devices cannot duplicate ID
        const now=new Date().toISOString();
        await setDoc(ref,{id:entryId,templateId:t.id,name:t.name,category:t.category||'生活',dueDate:due,amount:null,paid:false,paidDate:'',scope,createdAt:now,updatedAt:now});
      }
    }
  }finally{generating=false;}
}
function download(content,name,type){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),20000)}
async function exportData(){const data={};for(const k of ['bills','events','templates']){const snapshot=await getDocs(collection(db,itemsPath(k)));data[k]=snapshot.docs.map(d=>({id:d.id,...d.data()}))}download(JSON.stringify({format:'family-life-v2',scope:S.scope,exportedAt:new Date().toISOString(),data},null,2),`家庭生活_${S.scope}_${day()}.json`,'application/json')}
async function importData(file){if(!file)return;try{if(file.size>10*1024*1024)throw Error('檔案超過 10MB');const incoming=JSON.parse(await file.text());if(incoming.format!=='family-life-v2'||incoming.scope!==S.scope||!incoming.data||!['bills','events','templates'].every(k=>Array.isArray(incoming.data[k])))throw Error('備份格式或資料範圍不符');for(const k of ['bills','events','templates'])for(const x of incoming.data[k])if(!x||typeof x.id!=='string'||!/^[\w-]{1,150}$/.test(x.id)|| (x.scope && x.scope!==S.scope))throw Error('紀錄識別碼或存取範圍有誤');const replace=confirm('按「確定」：覆蓋目前範圍全部資料；按「取消」：下一步選擇合併或放棄。');const mode=replace?'replace':confirm('選擇合併現有資料？')?'merge':null;if(!mode)return;if(mode==='replace'&&S.scope==='shared'&&S.role!=='admin')throw Error('覆蓋家庭共用資料僅管理者可操作；請改用合併模式');await exportData();if(!confirm('已先下載目前資料備份。請確認檔案已保存，再按確定繼續。'))return;for(const k of ['bills','events','templates']){const current=await getDocs(collection(db,itemsPath(k)));if(mode==='replace'){for(const d of current.docs){if(S.scope==='shared')await updateDoc(d.ref,{deleted:true,deletedAt:new Date().toISOString()});else await deleteDoc(d.ref)}}for(const raw of incoming.data[k]){const ref=doc(db,itemsPath(k),raw.id),existing=mode==='merge'?await getDoc(ref):null;if(existing?.exists()){const before=existing.data();if(JSON.stringify(before)!==JSON.stringify(raw)&&!confirm(`資料衝突：${raw.name||raw.title||raw.id}\n確定用匯入版本取代？`))continue}const obj={...raw,id:raw.id,scope:S.scope};delete obj.ownerUid;await setDoc(ref,obj)}}alert('匯入已完成。');}catch(e){alert('匯入失敗：'+e.message)}finally{const el=$('#importFile');if(el)el.value=''}}
function csv(){const rows=[['項目','金額','期限','狀態','實際繳費日','分類'],...S.data.bills.map(b=>[b.name,b.amount??'',b.dueDate,b.paid?'已繳':'未繳',b.paidDate||'',b.category||''])];download('\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n'),`家庭繳費_${S.scope}_${day()}.csv`,'text/csv;charset=utf-8')}
async function actions(e){const target=e.target.closest('button');if(!target)return;const d=target.dataset;if(d.tab){S.tab=d.tab;render()}else if(d.scope){S.scope=d.scope;listen();render()}else if(d.month){S.date=addMonths(S.date+'-01',Number(d.month)).slice(0,7);S.selected=S.date+'-01';render()}else if(d.date){S.selected=d.date;render()}else if(d.year){S.year+=Number(d.year);render()}else if(d.yearmode){S.yearMode=d.yearmode;render()}else if(d.gomonth){S.date=d.gomonth;S.selected=S.date+'-01';render()}else if(d.add)edit(d.add);else if(d.edit)edit(d.edit,d.id);else if(d.action){switch(d.action){case 'close':$('#editor').close();break;case 'signout':await signOut(auth);break;case 'dismiss':S.notice='';render();break;case 'export':await exportData();break;case 'csv':csv();break;case 'import':$('#importFile').click();break;case 'password':{const pane=document.createElement('dialog');pane.innerHTML='<form method=dialog><h2>更換密碼</h2><label>新密碼（至少 8 碼）</label><input id=newPassword type=password minlength=8 autocomplete=new-password required><div class=foot><button value=cancel>取消</button><button class=primary value=save>確認修改</button></div></form>';document.body.appendChild(pane);pane.addEventListener('close',async()=>{try{if(pane.returnValue==='save'){const pw=pane.querySelector('#newPassword').value;if(pw.length<8)throw Error('密碼至少 8 碼');await updatePassword(S.user,pw);alert('密碼已更新')}}catch(ex){alert('密碼更新失敗（可能需要重新登入）：'+ex.message)}finally{pane.remove()}},{once:true});pane.showModal();break}case 'trash':{const out=$('#trashOutput'),html=[];for(const k of ['bills','events','templates']){const snap=await getDocs(collection(db,itemsPath(k,'shared')));for(const item of snap.docs){const x=item.data();if(x.deleted)html.push(`<div class="listitem"><span>${E(x.name||x.title)} (${E(k)})</span><button data-restore="${E(k)}" data-id="${E(item.id)}">還原</button></div>`)}}out.innerHTML=html.join('')||'<p>回收區目前沒有資料</p>';break}}}else if(d.restore){await updateDoc(doc(db,itemsPath(d.restore,'shared'),d.id),{deleted:false,deletedAt:null});target.closest('.listitem').remove()}}
async function handleSubmit(e){if(e.target.id==='loginForm'){e.preventDefault();const f=new FormData(e.target);await signInWithEmailAndPassword(auth,f.get('email'),f.get('password'))}if(e.target.id==='entryForm'){await save(e)}}
async function start(){if(!configured){$('#app').innerHTML='<section class="card"><h2>尚未設定 Firebase</h2><p>請先依照部署說明修改 firebase-config.js，再部署 GitHub Pages。</p></section>';return}const fb=initializeApp(cfg);auth=getAuth(fb);db=getFirestore(fb);try{await enableIndexedDbPersistence(db)}catch(e){console.warn('離線快取未啟用',e.code)}onAuthStateChanged(auth,async user=>{S.unsubs.forEach(fn=>fn());S.unsubs=[];S.user=user;if(!user){loginScreen();return}try{const member=await getDoc(doc(db,`${familyPath()}/members`,user.uid));if(!member.exists()||member.data().active===false){await signOut(auth);$('#message').innerHTML='<div class="notice">此帳號未獲家庭授權或已停用，請聯絡管理者。</div>';return}S.member=member.data();S.role=S.member.role==='admin'?'admin':'member';S.tab='home';listen();render()}catch(e){err(e)}})}
document.addEventListener('click',e=>actions(e).catch(err));document.addEventListener('submit',e=>{if(['loginForm','entryForm'].includes(e.target.id)){e.preventDefault();handleSubmit(e).catch(err)}});document.addEventListener('change',e=>{if(e.target.id==='importFile')importData(e.target.files[0])});$('#deleteEntry').addEventListener('click',()=>del().catch(err));if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(console.warn);start().catch(err);
